name = input("Enter your Name: ")
branch = input("Tell me your Branch: ")
gender = input("What is your Gender: ")
collegeName = input("What's your College Name: ")
age = int(input("Enter your Age: "))
print("Name:",name.capitalize())
print("Branch:",branch.upper())
print("Gender:",gender.capitalize())
print("College Name:",collegeName.title())
print("Age:",age)

